"$schema" = 'https://starship.rs/config-schema.json'

format = """
(fg:color_bi_pink)\
  (bg:color_bi_pink fg:color_bi_purple)\
$username\
[](bg:color_bi_purple fg:color_bi_pink)\
$directory\
[](bg:color_bi_blue fg:color_bi_purple)\
$git_branch\
$git_status\
[](bg:color_bi_blue fg:color_bi_blue)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[](bg:color_bg3 fg:color_bi_blue)\
$docker_context\
$conda\
[ ](bg:color_bg2 fg:color_bg3)\
"""

palette = 'gruvbox_dark'

[palettes.gruvbox_dark]
color_fg0 = '#fbf1c7'
color_bg1 = '#3c3836'
color_bg3 = '#665c54'
color_blue = '#3f7d99'         # Matte Blue
color_aqua = '#5b9b8a'          # Matte Aqua
color_green = '#7c9f4d'         # Matte Green
color_orange = '#d67a3a'        # Matte Orange
color_purple = '#7d4c91'        # Matte Purple
color_red = '#cc241d'           # Bright Red
color_yellow = '#d79921'        # Bright Yellow

# Bi flag colors with muted and matte tones
color_bi_pink = '#E88EB3'       # Original Pink
color_bi_purple = '#9B4F96'     # Matte Purple
color_bi_blue = '#5A91C8'       # Matte Blue

[os]
disabled = false
style = "bg:color_bi_pink fg:color_fg0"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = " 󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
EndeavourOS = ""
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
Pop = ""

[username]
show_always = true
style_user = "bg:color_bi_pink fg:color_fg0"  # Original Pink
style_root = "bg:color_bi_pink fg:color_fg0"  # Original Pink
format = '[ $user ]($style)'

[directory]
style = "fg:color_fg0 bg:color_bi_purple"  # Matte Purple
format = "[ $path ]($style)"
truncation_length = 5
truncation_symbol = "…/"

[git_branch]
#symbol = ""
style = "bg:color_bi_blue"  # Matte Blue
format = '[[ $symbol $branch ](fg:color_fg0 bg:color_bi_blue)]($style)'

[git_status]
style = "bg:color_bi_blue"  # Matte Blue
format = '[[($all_status$ahead_behind )](fg:color_fg0 bg:color_bi_blue)]($style)'

[nodejs]
symbol = ""
style = "bg:color_bi_blue"  # Matte Blue
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_bi_blue)]($style)'

[c]
symbol = " "
style = "bg:color_bi_blue"  # Matte Blue
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_bi_blue)]($style)'

[rust]
symbol = ""
style = "bg:color_bi_blue"  # Matte Blue
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_bi_blue)]($style)'

[golang]
symbol = ""
style = "bg:color_bi_blue"  # Matte Blue
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_bi_blue)]($style)'

[php]
symbol = ""
style = "bg:color_bi_blue"  # Matte Blue
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_bi_blue)]($style)'

[java]
symbol = ""
style = "bg:color_bi_blue"  # Matte Blue
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_bi_blue)]($style)'

[kotlin]
symbol = ""
style = "bg:color_bi_blue"  # Matte Blue
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_bi_blue)]($style)'

[haskell]
symbol = ""
style = "bg:color_bi_blue"  # Matte Blue
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_bi_blue)]($style)'

[python]
symbol = ""
style = "bg:color_bi_blue"  # Matte Blue
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_bi_blue)]($style)'

[docker_context]
symbol = ""
style = "bg:color_bg3"
format = '[[ $symbol( $context) ](fg:#83a598 bg:color_bg3)]($style)'

[conda]
style = "bg:color_bg3"
format = '[[ $symbol( $environment) ](fg:#83a598 bg:color_bg3)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:color_bg1"
format = '[[  $time ](fg:color_fg0 bg:color_bg1)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:color_green)'
error_symbol = '[](bold fg:color_red)'
vimcmd_symbol = '[](bold fg:color_green)'
vimcmd_replace_one_symbol = '[](bold fg:color_purple)'
vimcmd_replace_symbol = '[](bold fg:color_purple)'
vimcmd_visual_symbol = '[](bold fg:color_yellow)'

