"$schema" = 'https://starship.rs/config-schema.json'

format = """
[ ♡](bg:#e2bef1 fg:#101010)\
$time\
[](bg:#F5CDDE fg:#e2bef1)\
$directory\
[](fg:#F5CDDE bg:#c6f8e5)\
$git_branch\
[･✧:･](bg:#c6f8e5 fg:#101010)\
[ ](fg:#c6f8e5)\
"""

[time]
disabled = false
time_format = "%R"
style = "bg:#1d2230"
format = '[[ $time ](bg:#e2bef1 fg:#101010)]($style)'

[directory]
style = "fg:#101010 bg:#F5CDDE"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
style = "bg:#FCF392"
format = '[[ ✄ $branch ](fg:#101010 bg:#c6f8e5)]($style)'
