"$schema" = 'https://starship.rs/config-schema.json'

format = """
$time\
[](bg:#3B76F0 fg:#1C3A5E)\
$directory\
[](fg:#3B76F0 bg:#FCF392)\
$git_branch\
$git_status\
[ ](fg:#FCF392)\
"""

[time]
disabled = false
time_format = "%R"
style = "bg:#1d2230"
format = '[[ $time ](bg:#1C3A5E fg:#8DFBD2)]($style)'

[directory]
style = "fg:#E4E4E4 bg:#3B76F0"
format = "[ $path ]($style)"
truncation_length = 4
truncation_symbol = "…/"

[git_branch]
style = "bg:#FCF392"
format = '[[ $symbol $branch ](fg:#1C3A5E bg:#FCF392)]($style)'

[git_status]
style = "bg:#FCF392"
format = '[[($all_status$ahead_behind )](fg:#1C3A5E bg:#FCF392)]($style)'
